travis:
  secure:
    BINSTAR_TOKEN: rMxCK0nKa9WMckgLahcVTD3PHIuEH+FgZURf2f1mGr73/2uQTXUo7Y0NKrWvzTuGZN6zjzxIKp2eQaQBDfdO92Dv2c2Ln+FBNVTZfpHez6Nd6HJS68NSbeFI4Px8W6XaXxwhj/9etMF2vAoHlp9LhyR1j5wrs4QhIKfMoXWjm+tW3mAE3Gl4fDMQDZsVRXdklcoIjprWz1o/Ey3+UjKfPqvT7y5mIgvjLprbg2yWqQw2FEMZXqtaV0KYm5MoLhLgynkvmRuG9uwiCMiUQ4rg4BJRHSTklGxxOAjj7KgshZUI+iYvSUR8EInSM5P997hTj9No53/f1VIm2CS5Z9k5AsyNuHBdIeHCG+8rRuQH+RpNZIp/aiDae/Vwb5BQORgLjnYpqpq2LL7fzNRWpzA743ILLxbBpA3yQcbWDIZIJnrXBrz9xpZ2mUYZ0IzxnfYN0kGMb6oVU7+tImUF90LNijtJphhaecF6kSSj0/KZs/IPu/kava10Rks8A8cVHthQ1zLikDYFldsNELmuCs+dYQr/zNddSuxhVdni9cc6rKn6v1+uYZTShME4aQe3xzDCIzvNSV21PAnBjOmL5ZQVfmLRHFHFQWvt94pMWGhICk/Xp+r+EtouCE2ur+cpkxwF9iDL6nNQbvDmnG593GpOJP988cEKtf0Xky17Lm4GL7w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
