travis:
  secure:
    BINSTAR_TOKEN: PPO+1N3BDWnAm0IL2x7sFPlN6LrczVnICeayu83ZnDYrmBBYP/jpDz6sLVREoTqq8Qw/MR+yeBb0clXN1s16nwZxOBCJBvRjXT4B2NjS0H7g4x2FkJVBqilmP4T6C+4Y4mpNxb5rOUAF5/R/ESpJtFJlrjooQviwjueLRH+PEDW2haaNAXD7eD1DmXHQcpkOHbHbN5RnpWfBoWUAt/4HAIASEzwjPMGmYfCYzt9fbV39re0x7+n3A0PV3OjlzAAab7oeXK/mVXm+mxiqBXi9ggHgFjhQemb/eJmVwtYWhK/qfV2ZADHcXiMv1SqHF8vsRZEOFdIy4+SP38yXocxldrY1y755LK9G8tWWY5PqEbfuo+Wic8h9I1BrpdCsNi2HDuazaRNoGFDYr1rspZbOs0Z6TQtEWHZn/1yGfUrTl3dNebmz2fL7Md3ykAGz9Yyun/h5n2hOKnCLMG2DJXd7KNRgJ5+mxb0WEw+UD844yWvoH+PhJoOSl8TglxSgtG+qMX54IubmSWbjp2DYxBRteNtFS7LaHgPjEHrOuGGULW2cSigiDlY1POv+nmwe+sTEkVVQ0vh5RmVQ5eEhDmJcQs29SSpQW0HCHzk0WSvcgxT+WXTcoCuyn9dAWom4lXmxQSTYttW36H8N1Bi4RZ2D2fM6zcA2KBMih9PIuyUsDXY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
