travis:
  secure:
    BINSTAR_TOKEN: g4D7DSYWl5NUNRQoaUo5+A352KlMx9B/eH2/GSkYBLAy/C/rqLGs/AEWohGkB4emX2JBAVvf0xEOtcIBNiMxMcaYYDDv1+NdG6pMSaTki+l2yZYOtGJdrN20wfv8A7m8NFeFA6hOIJOuIixyyyjNCTB46qjC2rbGOtasIn4wruA2T5Y6IzAOMPXZ0998MUuVupUn3UzY6cfKh1sOLRQKjepZalfxr0T8FScNqOPRTrzjydZJn2y9QCFa7L449MK2NlFml7nVjzVKMcCoQ0X6LfFhN0SZ1dUuXGW+rqFX/Q0L8R4MwCrfobWjbdlvfQ1rNetilkHXlH2JxDk1bWSf8A4yOIg0YjR2NKy6WOL7wLjmTxsVWPjn+2BLtcRM8JbgQBNvx/Omot6uQUsYcvYXwsFaOBodAMV/xkzsAhefDhI7bv4x5/ZO3Rpft+BDAuSCYcISX817DSd+WHY+J9Kyf9q9TcJiv0A1TKSOBksSyTJ9r01DNyojYL1dc1fa3I8gE0/tSYsPChFjiDY74XmdSKEMWsjNevDrsBf0k78kyGuHwfVwtBP4yg3NJYe1iAEIElP/OETAwZ7vN2ScXc+AHwg1DotNQ8kaIOg/zlHGK38Kmq0JrQPF1e49ZHdMBQPKjIdiDVTiLB1t+eANqp//lPy6XQ2T3NOOKYxY+4xmDZg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
